version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    networks:
      - app-network

  paypal-mock:
    build:
      context: .
      dockerfile: mocks/paypal/Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped

  stripe-mock:
    build:
      context: .
      dockerfile: mocks/stripe/Dockerfile
    ports:
      - "8082:8082"
    restart: unless-stopped 

networks:
  app-network:
    driver: bridge