services:
  paypal-mock:
    build:
      context: .
      dockerfile: mocks/paypal/Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  stripe-mock:
    build:
      context: .
      dockerfile: mocks/stripe/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8082/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: test/Dockerfile
    command: sh -c "sleep 2 && go test ./..."
    depends_on:
      paypal-mock:
        condition: service_healthy
      stripe-mock:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PAYPAL_MOCK_URL=http://paypal-mock:8081
      - STRIPE_MOCK_URL=http://stripe-mock:8082
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    networks:
      - app-network
    depends_on:
      paypal-mock:
        condition: service_healthy
      stripe-mock:
        condition: service_healthy

networks:
  app-network:
    driver: bridge